name: Test unitaires

on:
  push:
    branches: [ "main", "test-unitaire" ]
  pull_request:
    branches: [ "main", "test-unitaire" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglfw3 libopenal1

      - name: Grant execute permission for gradlew
        run: chmod +x Game/gradlew

      - name: Build and test with Gradle
        run: ./gradlew build -Pheadless
        working-directory: ./Game